# Generated by Django 3.1.7 on 2021-02-27 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=30, verbose_name='email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('position', models.CharField(max_length=30, verbose_name='job')),
                ('department', models.CharField(max_length=50, verbose_name='department name')),
                ('birth_date', models.DateField(verbose_name='employee age')),
                ('salary', models.IntegerField(verbose_name='employee salary')),
                ('contract_type', models.CharField(choices=[(1, 'Permanent'), (2, 'Temporary')], max_length=9, verbose_name='type of contract')),
                ('status', models.CharField(choices=[(1, 'Active'), (2, 'Passive')], max_length=7, verbose_name='employment status')),
                ('type', models.CharField(choices=[(1, 'Full-Time'), (2, 'Part-Time')], max_length=9, verbose_name='type of employment')),
                ('ethnicity', models.CharField(max_length=32, verbose_name='employee ethnicity')),
                ('gender', models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=6, verbose_name='employee gender')),
                ('risk', models.IntegerField(verbose_name='risk of exit')),
                ('compa', models.IntegerField(verbose_name='compa ratio')),
                ('tenure', models.IntegerField(verbose_name='tenure')),
                ('start_date', models.DateField(verbose_name='employee started work')),
                ('hours', models.IntegerField(verbose_name='scheduled hours')),
                ('potenial', models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=16, verbose_name='potenial')),
                ('performance', models.CharField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], max_length=7, verbose_name='performance rating')),
                ('overtime', models.CharField(choices=[(1, 'Unknown'), (2, 'Yes'), (3, 'No')], max_length=16, verbose_name='overtime')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
